version: '3'
services:
  app:
    container_name: docker-node-ouath2
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - postgresql
  postgresql:
    container_name: postgresql
    image: postgresql
    ports:
      - '5432:5432'